### ISSUE TITLE
332 line Error

### ISSUE THREAD

**Issue by CDJung** [arson5012/cvMouseExtension#1]
Please check the function: Size cvMouseExtension::calculateAspectRatio(const Mat& image)
Some codes have an error from 332 line.

**Comment by arson5012** [comment]
I watched it too late. It's so different from the version I'm using, so I'm patching it now


----------------------------------------------------
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2024-08-14 (수) 15:24:30 (GMT+09:00)
Subject: [arson5012/cvMouseExtension] 332 line Error (Issue #1)

Please check the function: Size cvMouseExtension::calculateAspectRatio(const Mat& image)
Some codes have an error from 332 line.

**Comment by arson5012** [comment]
Patch completed
